"""Adding Role Table

Revision ID: 12669f15331e
Revises: 4e8f81ac7b63
Create Date: 2023-05-02 19:35:32.676464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12669f15331e'
down_revision = '4e8f81ac7b63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('roles_email_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'email')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('roles', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint('roles_email_key', 'roles', ['email'])
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
