"""adding cascade

Revision ID: 262fe50e80b0
Revises: fba8c26ea2af
Create Date: 2023-05-02 19:51:07.983271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262fe50e80b0'
down_revision = 'fba8c26ea2af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_resume_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_resume_id_fkey', 'users', 'resume', ['resume_id'], ['id'])
    # ### end Alembic commands ###
