"""Adding UserAccess Table

Revision ID: 4e8f81ac7b63
Revises: b0716caf833e
Create Date: 2023-05-01 22:37:04.042893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8f81ac7b63'
down_revision = 'b0716caf833e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_access_user_id'), 'user_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_access_user_id'), table_name='user_access')
    op.drop_table('user_access')
    # ### end Alembic commands ###
