"""empty message

Revision ID: 922d5bc2acf1
Revises: 
Create Date: 2023-05-01 01:29:05.121451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922d5bc2acf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
