"""empty message

Revision ID: b0716caf833e
Revises: ffd5e296e5b1
Create Date: 2023-05-01 16:35:33.211716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0716caf833e'
down_revision = 'ffd5e296e5b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
