"""Add foreign key constraint and unique constraint to User table

Revision ID: ced321c995a4
Revises: f9764b50fefa
Create Date: 2023-05-01 01:40:24.458899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced321c995a4'
down_revision = 'f9764b50fefa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_resume', 'resume', type_='unique')
    op.drop_constraint('resume_user_id_fkey', 'resume', type_='foreignkey')
    op.drop_column('resume', 'user_id')
    op.create_unique_constraint(None, 'users', ['resume_id'])
    op.create_foreign_key(None, 'users', 'resume', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('resume', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('resume_user_id_fkey', 'resume', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('unique_user_resume', 'resume', ['user_id'])
    # ### end Alembic commands ###
