"""empty message

Revision ID: f9764b50fefa
Revises: 922d5bc2acf1
Create Date: 2023-05-01 01:31:55.848124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9764b50fefa'
down_revision = '922d5bc2acf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_resume_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_resume_id_fkey', 'users', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
